This commit was manufactured by cvs2svn to create tag 'rel-1-20'.

diff --git a/Makefile.rules b/Makefile.rules
--- a/Makefile.rules
+++ b/Makefile.rules
@@ -1,18 +1,15 @@
-#################################################################
-#								#
-#			Makefile.rules				#
-#								#
-#  Author -							#
-#	Michael John Muuss					#
-#								#
-#  Source -							#
-#	SECAD/VLD Computing Consortium, Bldg 394		#
-#	The U. S. Army Ballistic Research Laboratory		#
-#	Aberdeen Proving Ground, Maryland  21005		#
-#								#
-#  $Header$		#
-#								#
-#################################################################
+#
+#			Makefile.rules
+#
+#  Source -
+#	SECAD/VLD Computing Consortium, Bldg 394
+#	The U. S. Army Ballistic Research Laboratory
+#	Aberdeen Proving Ground, Maryland  21005
+#
+#  This Makefile draws heavily on the experiences of Doug Gwyn's
+#  VLD Standard Makefile, and Doug Kingston's MMDF Global Makefile.
+#	-Mike Muuss, BRL/SECAD, August 1986.
+
 
 #  Define default list of targets to be made
 all:		${PRODUCTS}
@@ -51,6 +48,15 @@ flow:		${HEADERS} ${CFILES}
 xref:		${HEADERS} ${CFILES}
 	cxref -c -s -w132 -I${INCDIR} ${CFILES} > ${SRCDIR}.xref
 
+#test:		${PRODUCTS} ${TFILES}
+#	${PRODUCT} < ${PRODUCT}.in > ${PRODUCT}.out 2> ${PRODUCT}.err
+#	@if cmp ${PRODUCT}.exp ${PRODUCT}.out ; \
+#	then	echo 'Tested okay' ; \
+#	else	echo 'Test failed; differences:' ; \
+#		diff ${PRODUCT}.exp ${PRODUCT}.out ; \
+#		exit 1 ; \
+#	fi
+
 compare:	all
 	for prod in ${PRODUCTS} ; \
 		do	cmp ${BINDIR}/$$prod $$prod; \
@@ -87,7 +93,6 @@ uninst-stub:
 		    ${MANDIR}${MANSECTION}/$$man.bak 2>/dev/null ; \
 	done
 
-# Handle all phases of final installation
 install:	all
 	-@if test -n "${PRODUCTS}" ; \
 	then	$(MAKE) $(MFLAGS) -$(MAKEFLAGS) inst-prod ; \
@@ -102,7 +107,6 @@ install:	all
 	fi
 	-@sh -c "if test `${GETHOST}` = ${MASTERHOST} ; then $(MAKE) inst-dist; else exit 0 ; fi"
 
-# Install all products
 inst-prod:	${PRODUCTS}
 	-@for prod in ${PRODUCTS} ; \
 	do	if cmp -s ${BINDIR}/$$prod $$prod; \
@@ -148,7 +152,7 @@ inst-stub:
 # but that would miss routines that were not configured in a particular system.
 inst-dist:
 	-rm -fr ${DISTRIBUTION}/${SRCDIR}/*
-	-${INS} ./Makefile.loc Makefile *.[hcfs] ${SHFILES} \
+	-${INS} ./Makefile.loc Makefile *.[hcs] ${SHFILES} \
 		*.${MANSECTION} *.${MANSECTION}.stub \
 		*.doc \
 		${DISTRIBUTION}/${SRCDIR}/.
